[app]
name = "PageTop Application"
description = "Developed with the amazing PageTop framework."
# Idioma (localizaci贸n) predeterminado.
language = "en-US"
# Tema predeterminado.
theme = "Minimal"
# R贸tulo al inicio: "Off", "Slant", "Small", "Speed" o "Starwars".
startup_banner = "Small"
# Traza de la ejecuci贸n: "Error", "Warn", "Info", "Debug" o "Trace".
# Ejemplos: "Error,actix_server::builder=Info,tracing_actix_web=Debug".
tracing = "Info"

[webserver]
# Configuraci贸n opcional del servidor web.
# Usar bind_address = "" para deshabilitar el servidor web.
bind_address = "localhost"
bind_port = 8088
